server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hmall?useSSL=false
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:change-me}
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: userservice
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    virtual-host: ${RABBITMQ_VHOST:/}
    username: ${RABBITMQ_USERNAME:change-me}
    password: ${RABBITMQ_PASSWORD:change-me}
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: HH:mm:ss:SSS
mybatis-plus:
  type-aliases-package: com.hmall.user.pojo
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
